import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const source = resolve(root, 'sites/tce-go-ti-2026/dist');
const staging = resolve(root, 'sites/tce-go-ti-2026/staging');
const repository = process.env.GITHUB_REPOSITORY?.split('/').at(-1) ?? '';
const commitSha = process.env.GITHUB_SHA ?? 'unavailable-local-snapshot';
const buildTimestamp = process.env.STAGING_BUILD_TIMESTAMP ?? new Date().toISOString();
await rm(staging, { recursive: true, force: true });
await mkdir(staging, { recursive: true });
await cp(source, staging, { recursive: true });
await cp(resolve(root, 'sites/tce-go-ti-2026/staging-source/diagnostic.html'), resolve(staging, 'diagnostic.html'));
await cp(resolve(root, 'sites/tce-go-ti-2026/staging-source/diagnostic.js'), resolve(staging, 'diagnostic.js'));
await cp(resolve(root, 'sites/tce-go-ti-2026/staging-source/staging-diagnostics.html'), resolve(staging, 'staging-diagnostics.html'));
const indexPath = resolve(staging, 'index.html');
const index = await readFile(indexPath, 'utf8');
const stagingNav = '<nav aria-label="Staging navigation"><a href="#today">Hoje</a> <a href="#curriculum">Currículo</a> <a href="#diagnostic">Diagnóstico</a> <a href="#questions">Questões</a> <a href="#reviews">Revisões</a> <a href="#progress">Progresso</a> <a href="#settings">Configurações</a></nav>';
const stagingSections = '<section id="curriculum" class="card"><h2>Currículo</h2><p>Currículo do Exam Pack ativo.</p></section><section id="diagnostic" class="card"><h2>Diagnóstico</h2><p><a href="./diagnostic.html">Abrir diagnóstico O1</a>.</p></section><section id="settings" class="card"><h2>Configurações</h2><p>Preferências da prévia.</p></section>';
await writeFile(indexPath, index.replace('<body>', '<body><div class="staging-ribbon" role="status">STAGING / PREVIEW</div>').replace('<header', `${stagingNav}<header`).replace('</main>', `${stagingSections}</main>`));
const stylesPath = resolve(staging, 'styles.css');
const styles = await readFile(stylesPath, 'utf8');
await writeFile(stylesPath, `${styles}\n.staging-ribbon { padding: .35rem 1rem; color: #fff; background: #7c2d12; font-weight: 700; text-align: center; }\nnav[aria-label="Staging navigation"] { display: flex; flex-wrap: wrap; gap: .75rem; padding: .75rem 1rem; }\n`);
const manifestPath = resolve(staging, 'manifest.webmanifest');
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
manifest.name = 'StudyOS — STAGING / PREVIEW — TCE-GO TI 2026';
manifest.short_name = 'StudyOS STAGING';
manifest.id = './';
await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
const swPath = resolve(staging, 'sw.js');
const sw = await readFile(swPath, 'utf8');
await writeFile(swPath, sw.replace(/studyos-tce-go-f10-v1/g, 'studyos-tce-go-staging-v1').replace("'./o1-diagnostics.html', './o1-diagnostics.js',", "'./o1-diagnostics.html', './o1-diagnostics.js', './diagnostic.html', './diagnostic.js', './staging-diagnostics.html', './staging-meta.json',"));
await writeFile(resolve(staging, 'staging-meta.json'), `${JSON.stringify({ buildVersion: 'o1.5-staging', commitSha, buildTimestamp, repository: repository || 'unavailable-local-repository', examId: 'tce-go-ti-2026', schemaVersions: 'mastery:1, diagnostic-run:1', storageVersion: 1, basePath: repository ? `/${repository}/` : './' }, null, 2)}\n`);
if (!repository) console.warn('GITHUB_REPOSITORY unavailable; local preview metadata uses relative base path.');
console.log(`staging build ready: ${staging}`);
